scrape_configs:
  - job_name: prometheus
    scrape_interval: 5s
    static_configs:
      - targets:
        - prometheus:9090
  - job_name: 'blackbox'
    scrape_interval: 5s
    metrics_path: /probe
    params:
      module: [http_2xx]  # Look for a HTTP 200 response.
    static_configs:
      - targets:
        - http://blazor:8080/health #Catalog API
    relabel_configs:
      - source_labels: [__address__]
        target_label: __param_target
      - source_labels: [__param_target]
        target_label: instance
      - target_label: __address__
        replacement: blackbox:9115
  - job_name: 'metrics-blazor'
    scrape_interval: 5s 
    static_configs:
      - targets: ['carlos_blazor:8080']

  - job_name: 'Metrics'
  scrape_interval: 5s
  static_configs:
    - targets: ['otel-collector:1234']
#xd