apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  namespace: carlos
  name: carlos-web-ingress
spec:
  ingressClassName: nginx
  rules:
  - host: carlos-kube.duckdns.org
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: carlos-web-service
            port:
              number: 80