name: carlosRunner
on: [push] 
jobs: 
  DeployingPipeline: 
    runs-on: carloslabel
    steps: 
     - name: "cleaning"
       run: |
        rm -rf ./CarlosTicketsRUs
     - name: "cloning"
       run: git clone https://github.com/CarlosBlanco1/CarlosTicketsRUs.git
     - name: "build"
       run: | 
        cd ./CarlosTicketsRUs/StagingCarlos
        docker compose up --build -d
     - name: "run integration tests"
       run: |
        cd ./CarlosTicketsRUs/
        docker run --rm --network="container:dbcontainer" -v "$(pwd):/app" -w /app/TestTicket -e DOTNET_CLI_HOME="/tmp/dotnet" --user $(id -u):$(id -g) mcr.microsoft.com/dotnet/sdk:8.0 dotnet test
     - name: "run linting"
       run: |
        cd ./CarlosTicketsRUs/
        docker run --rm -v "$(pwd):/app" -w /app mcr.microsoft.com/dotnet/sdk:8.0 -dotnet format --verify-no-changes --severity warn 
     - name: "build warnings fail"
       run: |
        cd ./CarlosTicketsRUs/
        docker run --rm -v "$(pwd):/app" -w /app/ mcr.microsoft.com/dotnet/sdk:8.0 -dotnet build -WarnAsError 

    # - uses: actions/checkout@v2

    # - name: "Notifies Teams Channel"
    #   uses: dchourasia/ms-teams-notification@1.0 
    #   if: always()
    #   with:
    #     github-token: ${{ github.token }}
    #     webhook-uri: ${{ secrets.CARLOS_WEBHOOK }}
        

