name: carlosRunner
on: [push] 
jobs: 
  DeployingPipeline: 
    runs-on: carloslabel
    steps: 
     - name: "cleaning"
       run: |
        rm -rf ./CarlosTicketsRUs
     - name: "cloning"
       run: git clone https://github.com/CarlosBlanco1/CarlosTicketsRUs.git
     - name: "build"
       run: | 
        cd ./CarlosTicketsRUs/StagingCarlos
        docker compose up --build -d
     - name: "run integration tests"
       run: |
        cd ./CarlosTicketsRUs/TestTicket/
        dotnet test 
     - name: "run unit tests"
       run: |
        cd ./CarlosTicketsRUs/UnitTests/
        dotnet test 
     - name: "run linting"
       run: |
        cd ./CarlosTicketsRUs/
        docker run --rm -v "$(pwd):/app" -w /app -e DOTNET_CLI_HOME="/tmp/dotnet" --user $(id -u):$(id -g) mcr.microsoft.com/dotnet/sdk:8.0 dotnet format --verify-no-changes --severity warn 
     - name: "build warnings fail"
       run: |
        cd ./CarlosTicketsRUs/
        docker run --rm -v "$(pwd):/app" -w /app/ -e DOTNET_CLI_HOME="/tmp/dotnet" --user $(id -u):$(id -g) mcr.microsoft.com/dotnet/sdk:8.0 dotnet build

     - name: "network setup"
       run: |
        docker network rm -f carlos_network carlos_prometheus
        docker network rm -f carlos_network carlos_grafana
        docker network rm -f carlos_network carlos_blackbox 
        docker network rm -f carlos_network carlos_loki
        docker network rm -f carlos_network carlos_zipkin
        docker network rm -f carlos_network carlos_otel
        docker network create carlos_network

     - name: "prometheus" 
       run: |
        cd ./CarlosTicketsRUs/
        docker rm -f carlos_prometheus
        docker run --rm -d --name carlos_prometheus --network carlos_network --hostname prometheus -p 5767:9090 -v "$(pwd)/prometheus/prometheus.yml:/etc/prometheus/prometheus.yml" prom/prometheus:v2.43.0
     - name: "grafana" 
       run: |
        cd ./CarlosTicketsRUs/
        docker rm -f carlos_grafana
        docker run --rm -d --name carlos_grafana --network carlos_network -e GF_AUTH_ANONYMOUS_ENABLED=true -e GF_AUTH_ANONYMOUS_ORG_ROLE=Admin -e GF_AUTH_DISABLE_LOGIN_FORM=true -p 5768:3000 -v "$(pwd)/grafana/provisioning:/etc/grafana/provisioning" -v grafana-data:/var/lib/grafana grafana/grafana:9.4.7
     - name: "blackbox" 
       run: |
        cd ./CarlosTicketsRUs/
        docker rm -f carlos_blackbox
        docker run --rm -d --name carlos_blackbox --network carlos_network -p 5766:9115 -v "$(pwd)/blackbox/blackbox.yml:/etc/blackbox/blackbox.yml" prom/blackbox-exporter:v0.23.0 --config.file=/etc/blackbox/blackbox.yml
     - name: "loki" 
       run: |
        cd ./CarlosTicketsRUs/
        docker rm -f carlos_loki
        docker run --rm -d --name carlos_loki --network carlos_network -p 5100:5100 -v "$(pwd)/loki/loki.yml:/etc/loki/local-config.yaml" -v loki:/data/loki grafana/loki:2.8.0 --config.file=/etc/loki/local-config.yaml
     - name: "zipkin" 
       run: |
        cd ./CarlosTicketsRUs/
        docker rm -f carlos_zipkin
        docker run --rm -d --name carlos_zipkin --network carlos_network -p 9411:9411 openzipkin/zipkin
     - name: "otel"
       run: |
        cd ./CarlosTicketsRUs/
        docker rm -f carlos_otel
        docker run --rm -d --name carlos_otel --network carlos_network --hostname otel -v $(pwd)/otel/otel.yml:/etc/otel-collector-config.yaml -p 4417:4417 -p 7200:7200 -p 8988:8988 -p 8989:8989 otel/opentelemetry-collector-contrib:0.75.0 --config=/etc/otel-collector-config.yaml

     #- uses: actions/checkout@v2

     #- name: "Notifies Teams Channel"
     #  uses: dchourasia/ms-teams-notification@1.0 
     #  if: always()
     #  with:
     #     github-token: ${{ github.token }}
     #     webhook-uri: ${{ secrets.CARLOS_WEBHOOK }}
     #had to wait

