name: carlosRunner
on: [push] 
jobs: 
  DeployingPipeline: 
    runs-on: carloslabel
    steps: 
     - name: "cleaning"
       run: |
        rm -rf ./CarlosTicketsRUs
     - name: "cloning"
       run: git clone https://github.com/CarlosBlanco1/CarlosTicketsRUs.git
     - name: "build"
       run: | 
        cd ./CarlosTicketsRUs/StagingCarlos
        docker compose up --build -d
     - name: "run integration tests"
       run: |
        cd ./CarlosTicketsRUs/TestTicket/
        dotnet test 
     - name: "run unit tests"
       run: |
        cd ./CarlosTicketsRUs/UnitTests/
        dotnet test 
     - name: "run linting"
       run: |
        cd ./CarlosTicketsRUs/
        docker run --rm -v "$(pwd):/app" -w /app -e DOTNET_CLI_HOME="/tmp/dotnet" --user $(id -u):$(id -g) mcr.microsoft.com/dotnet/sdk:8.0 dotnet format --verify-no-changes --severity warn 
     - name: "build warnings fail"
       run: |
        cd ./CarlosTicketsRUs/
        docker run --rm -v "$(pwd):/app" -w /app/ -e DOTNET_CLI_HOME="/tmp/dotnet" --user $(id -u):$(id -g) mcr.microsoft.com/dotnet/sdk:8.0 dotnet build
     - name: "prometheus" 
       run: |
        cd ./CarlosTicketsRUs/
        docker run --rm -d --name carlos_prometheus prom/prometheus:v2.43.0
        docker stop carlos_prometheus 
        docker rm -f carlos_prometheus
        docker run --rm -d --name carlos_prometheus --hostname prometheus -p 4767:9090 -v "$(pwd)/prometheus/prometheus.yml:/etc/prometheus/prometheus.yml" prom/prometheus:v2.43.0
     - name: "grafana" 
       run: |
        cd ./CarlosTicketsRUs/
        docker run --rm -d --name carlos_grafana grafana/grafana:9.4.7
        docker stop carlos_grafana 
        docker rm -f carlos_grafana
        docker run --rm -d --name carlos_grafana -e GF_AUTH_ANONYMOUS_ENABLED=true -e GF_AUTH_ANONYMOUS_ORG_ROLE=Admin -e GF_AUTH_DISABLE_LOGIN_FORM=true -p 4768:3000 -v "$(pwd)/grafana/provisioning:/etc/grafana/provisioning" -v grafana-data:/var/lib/grafana grafana/grafana:9.4.7
     - name: "blackbox" 
       run: |
        cd ./CarlosTicketsRUs/
        docker run --rm -d --name carlos_blackbox prom/blackbox-exporter:v0.23.0
        docker stop carlos_blackbox 
        docker rm -f carlos_blackbox
        docker run --rm -d --name carlos_blackbox -p 4766:9115 -v "$(pwd)/blackbox/blackbox.yml:/etc/blackbox/blackbox.yml" prom/blackbox-exporter:v0.23.0 --config.file=/etc/blackbox/blackbox.yml
     - name: "loki" 
       run: |
        cd ./CarlosTicketsRUs/
        docker run --rm -d --name carlos_loki grafana/loki:2.8.0
        docker stop carlos_loki 
        docker rm -f carlos_loki
        docker run --rm -d --name carlos_loki -p 3100:3100 -v "$(pwd)/loki/loki.yml:/etc/loki/local-config.yaml" -v loki:/data/loki grafana/loki:2.8.0 --config.file=/etc/loki/local-config.yaml
     - name: "zipkin" 
       run: |
        cd ./CarlosTicketsRUs/
        docker run --rm -d --name carlos_zipkin openzipkin/zipkin
        docker stop carlos_zipkin 
        docker rm -f carlos_zipkin
        docker run --rm -d --name carlos_zipkin -p 9411:9411 openzipkin/zipkin
     - name: "otel"
       run: |
        cd ./CarlosTicketsRUs/
        docker run --rm -d --name carlos_otel otel/opentelemetry-collector-contrib:0.75.0
        docker stop carlos_otel && docker rm -f carlos_otel
        docker run --rm -d --name carlos_otel --hostname otel -v $(pwd)/otel/otel.yml:/etc/otel-collector-config.yaml -p 4317:4317 -p 9200:9200 -p 8888:8888 -p 8889:8889 otel/opentelemetry-collector-contrib:0.75.0 --config=/etc/otel-collector-config.yaml

     #- uses: actions/checkout@v2

     #- name: "Notifies Teams Channel"
     #  uses: dchourasia/ms-teams-notification@1.0 
     #  if: always()
     #  with:
     #     github-token: ${{ github.token }}
     #     webhook-uri: ${{ secrets.CARLOS_WEBHOOK }}

