name: carlosRunner
on: [push] 
jobs: 
  DeployingPipeline: 
    runs-on: carloslabel
    steps: 
     - name: "cleaning"
       run: rm -rf ./CarlosTicketsRUs
     - name: "cloning"
       run: git clone https://github.com/CarlosBlanco1/CarlosTicketsRUs.git
     - name: "build"
       run: | 
        cd ./CarlosTicketsRUs/StagingCarlos
        docker compose up --build -d
     - name: "run integration tests"
       run: |
        docker run --rm -v "$(pwd)/TestTicket:/app" -w /app/ mcr.microsoft.com/dotnet/sdk:8.0 dotnet test -p app/TestTicket/*.csproj
     - name: "run linting"
       run: |
        docker run --rm -v "$(pwd):/app" -w /app/ mcr.microsoft.com/dotnet/sdk:8.0 -dotnet format --verify-no-changes --severity warn -p app/
     - name: "build warnings fail"
       run: |
        docker run --rm -v "$(pwd):/app" -w /app/ mcr.microsoft.com/dotnet/sdk:8.0 -dotnet build -WarnAsError -p app/

     - uses: actions/checkout@v2

     - name: "Notifies Teams Channel"
       uses: dchourasia/ms-teams-notification@1.0 
       if: always()
       with:
         github-token: ${{ github.token }}
         webhook-uri: ${{ secrets.CARLOS_WEBHOOK }}


        

