name: Pull Request Workflow

on:
  pull_request:
    types: [opened]

jobs:
  deploy-to-kubernetes:
    runs-on: self-hosted

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: deploy kubernetes environment
      run: |
        export PULL_REQUEST_ID = ${{ github.event.pull_request.number }}
        kubectl create namaspace carlos-pr-$PULL_REQUEST_ID
 
