name: Pull Request Workflow

on:
  pull_request:
    types: [opened, reopened]

jobs:
  deploy-to-kubernetes:
    runs-on: self-hosted

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: deploy kubernetes environment
        run: |
          export PULL_REQUEST_ID=${{ github.event.pull_request.number }}
          kubectl create namespace carlos-pr-$PULL_REQUEST_ID || true

          kubectl -n carlos-pr-$PULL_REQUEST_ID delete configmap blazor-web-postgres-init --from-file=init.sql || true
          kubectl -n carlos-pr-$PULL_REQUEST_ID create configmap blazor-web-postgres-init --from-file=init.sql

