name: Pull Request Workflow

on:
  pull_request:
    types: [opened]

jobs:
  deploy-to-kubernetes:
    runs-on: self-hosted

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    # - name: Run tests
    #   run: |
    #     # Your testing commands here

